### ISSUE TITLE
Unable to deserialize response: pickle data was truncated

### ISSUE THREAD

**Issue by BradleyRR** [vterron/fear-and-greed#26]
I'm getting an error when I run the most basic "fear_and_greed.get()" command. I've tried uninstalling and reinstalling these packages with no different results: 

- fear_and_greed
- requests
- requests_cache

Environment details: 
Python 3.10.11
Ubuntu

Here are the error details from the  Apache Airflow logs:

```
[2023-08-28, 00:00:07 UTC] {base.py:427} ERROR - Unable to deserialize response: pickle data was truncated
[2023-08-28, 00:00:07 UTC] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/bradl/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/bradl/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/bradl/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/c/Users/bradl/Dropbox/Python/airflow_home/dags/dag_scrape_fear_and_greed.py", line 49, in get_fear_and_greed
    fear_and_greed = fear_and_greed.get()
  File "/home/bradl/.local/lib/python3.10/site-packages/fear_and_greed/cnn.py", line 59, in get
    response = fetcher()["fear_and_greed"]
  File "/home/bradl/.local/lib/python3.10/site-packages/fear_and_greed/cnn.py", line 48, in __call__
    r = requests.get(URL, headers=headers)
  File "/home/bradl/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/bradl/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bradl/.local/lib/python3.10/site-packages/requests_cache/session.py", line 158, in request
    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore
  File "/home/bradl/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bradl/.local/lib/python3.10/site-packages/requests_cache/session.py", line 205, in send
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
  File "/home/bradl/.local/lib/python3.10/site-packages/requests_cache/session.py", line 233, in _send_and_cache
    self.cache.save_response(response, actions.cache_key, actions.expires)
  File "/home/bradl/.local/lib/python3.10/site-packages/requests_cache/backends/base.py", line 91, in save_response
    self.responses[cache_key] = cached_response
  File "/home/bradl/.local/lib/python3.10/site-packages/requests_cache/backends/sqlite.py", line 309, in __setitem__
    self._write(key, value)
  File "/home/bradl/.local/lib/python3.10/site-packages/requests_cache/backends/sqlite.py", line 331, in _write
    con.execute(
sqlite3.DatabaseError: database disk image is malformed
```

**Comment by vterron** [comment]
Looks like a problem with the `requests-cache` [file-based cache](https://requests-cache.readthedocs.io/en/stable/user_guide/files.html).

`fear-and-greed` [uses](https://github.com/vterron/fear-and-greed/blob/2a3e44360572bbebaae7ae4a5790872ecc30abf6/src/fear_and_greed/cnn.py#L14C29-L14C48) for the cache a filed named `cnn_cache` stored in a [temporary directory](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir).

What's the output of...

```
❯ python3 -c 'import os.path; import tempfile; print(os.path.join(tempfile.gettempdir(), "cnn_cache"))'
````
... ? Can you try deleting that file?

**Comment by BradleyRR** [comment]
The output of that was "/tmp/cnn_cache" (I'm using WSL V1). 

![image](https://github.com/vterron/fear-and-greed/assets/21159966/f6caf284-0e98-4d48-9448-668a34d341d9)

I did find and delete that file, and then I uninstalled and re-installed the fear and greed package. 

That did result in a new error, now the "fear_and_greed.get()" command returns this error:

![image](https://github.com/vterron/fear-and-greed/assets/21159966/1b84d3bb-b9b8-421f-9c3b-78f1a32675a6)

"no such table: responses."

**Comment by BradleyRR** [comment]
Very strange... 

"cnn_cache.sqlite" is re-created by the way, but it's completely empty.

**Comment by vterron** [comment]
That's indeed strange. It seems we should run into that error only if the cache file is deleted [while the application is running](https://github.com/requests-cache/requests-cache/issues/69#issuecomment-785473601) — which is not the case here. I don't know what's happening here but it seems to be a `requests-cache` issue (perhaps related to the fact you're using WSL V1?).

In order to unblock you: would it help if I add to `fear_and_greed.get()` an option to disable caching?

**Comment by BradleyRR** [comment]
You know what? I tried it again today, and it's working now. It suddenly started working yesterday, for some reason. I didn't change anything. Very strange.

I guess deleting the cache eventually caused it to rebuild correctly...? Who knows. 

In any case, I'm in business, thank you very much for your help. :)

![image](https://github.com/vterron/fear-and-greed/assets/21159966/26cfc4dd-e988-441b-b2b0-b305879df529)

**Comment by vterron** [comment]
Happy to hear! Please reopen if this ever becomes an issue again.
